import { useEffect, useState } from 'react';
import Head from 'next/head';
import List from '../components/List/List';
import ImageService from '../services/image.service';

export default function Home() {
  const [imageList, setImageList] = useState([]);
  const [pageNo, setPageNo] = useState(1);

  useEffect(() => {
    fetchImages();
  }, []);

  const fetchImages = () => {
    ImageService.fetchImageList(pageNo)
      .then((response) => {
        setImageList(() => {
          return [...imageList, ...response];
        });
      })
      .catch((error) => {
        console.error('Exception ImageService -> fetchImageList : ', error);
      });
  };

  return (
    <div>
      <Head>
        <title>Photo Grid</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <List data={imageList} viewItem={(image) => handleSelectedImage(image)} />
    </div>
  );
}
